spring:
  config:
    import: configserver:http://localhost:8071
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
      enabled: true

server:
  port: 8081